stages:
  - test

default:
  image: python:3

.base_test:
  stage: test
  coverage: '/^TOTAL.*\s+(\d+\%)$/'
  except:
    - standalone
  before_script:
    - apt-get update && apt-get install -y zip
    - pip install tox
    - ./bin/test_standalone.sh

test-docker:
  image: docker:latest
  services:
    - name: docker:dind
      alias: localhost
  except:
    - standalone
  before_script:
    - apk add --no-cache curl python3 python3-dev gcc libffi-dev musl-dev openssl-dev
    - pip3 install twine
  script:
    - ./bin/test-docker.sh

validate-readme:
  image: python:3
  except:
    - standalone
  before_script:
    - pip install sphinx
  script:
    - ./bin/check_readme.sh

test-2.7:
  extends: .base_test
  image: python:2.7
  script:
    - tox -e py27

test-3.4:
  extends: .base_test
  image: python:3.4
  script:
    - tox -e py34

test-3.5:
  extends: .base_test
  image: python:3.5
  script:
    - tox -e py35

test-3.6:
  extends: .base_test
  image: python:3.6
  script:
    - tox -e py36

test-3.7:
  extends: .base_test
  image: python:3.7
  script:
    - tox -e py37

test-3.8:
  extends: .base_test
  image: python:3.8
  script:
    - tox -e py38

test-pypy-2:
  extends: .base_test
  image: pypy:2
  before_script:
    - pypy -m pip install tox
  script:
    - tox -e pypy

test-pypy-3:
  extends: .base_test
  image: pypy:3
  # TODO: figure out why this is failing in GL but not in Travis
  allow_failure: true
  before_script:
    - pypy3 -m pip install tox
  script:
    - tox -e pypy3
