#! /bin/sh

## Requires this script in your PATH:
##   https://github.com/git/git/blob/master/contrib/workdir/git-new-workdir

gitversion=$(git describe --tags)
rm -rf .standalone
if nwd_dump=$( git-new-workdir . .standalone standalone 2>&1 ); then
	./gen-standalone.py
	cp -p pypi-server-standalone.py .standalone
	cd .standalone
	git add .
	git ci -m "add pypi-server-standalone $gitversion"
else
	echo "failed due to: $nwd_dump" 
	exit 1
fi
